task_DEV-1
KatsiarynaBukraba/TAT_2018.1 pull request #1
Opened 2018-03-02 10:41 UTC by KatsiarynaBukraba

2018-03-02 11:31 UTC, IgorKheidorov requested changes

2018-03-02 11:31 UTC, IgorKheidorov commented on DuplicateSymbols.cs
> +    /// <summary>
Class can't be "about", bad comment

2018-03-02 11:31 UTC, IgorKheidorov commented on DuplicateSymbols.cs
> +
empty line

2018-03-02 11:31 UTC, IgorKheidorov commented on EntryPoint.cs
> +            DuplicateSymbols userString = new DuplicateSymbols(args[0]);
bad value name

2018-03-02 11:31 UTC, IgorKheidorov commented on DuplicateSymbols.cs
> +                }
empty string

2018-03-02 11:31 UTC, IgorKheidorov commented on DuplicateSymbols.cs
> +            return maxCount + 1;
Why +1? better int count = 1

2018-03-02 11:31 UTC, IgorKheidorov commented on EntryPoint.cs
> +        {
Check number of arguments

2018-03-02 11:31 UTC, IgorKheidorov commented on DuplicateSymbols.cs
> +        /// This method researches users string to found maximal series of duplicate symbols.
"This method researches..." bad comment, method do not research, it find or calculate

2018-03-03 09:23 UTC, IgorKheidorov requested changes

2018-03-03 09:23 UTC, IgorKheidorov commented on LineAnalysis/DuplicateSymbols.cs
> +    ///  This class contains methods for work with duplicate symbols.
duplicated

2018-03-03 09:23 UTC, IgorKheidorov commented on LineAnalysis/DuplicateSymbols.cs
> +    class DuplicateSymbols
Better DuplicateSymbolsCounter

2018-03-03 09:23 UTC, IgorKheidorov commented on LineAnalysis/DuplicateSymbols.cs
> +
Ha- Ham, its bug, not correct result returns in one case, look for

2018-03-03 11:07 UTC, AlexanderSoroka requested changes
readme.txt doesn't relate to the task, remove it from review

2018-03-03 11:07 UTC, AlexanderSoroka commented on LineAnalysis/DuplicateSymbolsCounter.cs
> +        private string UserString { get; set; }
bad property name - who guarantee that string always relates to user?

2018-03-03 11:07 UTC, AlexanderSoroka commented on LineAnalysis/DuplicateSymbolsCounter.cs
> +        public DuplicateSymbolsCounter(string args)
bad argument name, "value" is much better

2018-03-03 12:12 UTC, IgorKheidorov approved these changes

2018-03-03 12:12 UTC, IgorKheidorov commented on LineAnalysis/DuplicateSymbolsCounter.cs
> +    /// </summary>
DublicatedSymbols..

2018-03-03 12:12 UTC, IgorKheidorov commented on LineAnalysis/DuplicateSymbolsCounter.cs
> +        /// <summary>
Dublicated

2018-03-03 13:54 UTC, merged