task_DEV-3
KatsiarynaBukraba/TAT_2018.1 pull request #3
Opened 2018-03-06 19:11 UTC by KatsiarynaBukraba

2018-03-07 10:57 UTC, IgorKheidorov requested changes

2018-03-07 10:57 UTC, IgorKheidorov commented on task_DEV-3/EntryPoint.cs
> +
Rework to Parse and handle exceptions (as agreed in chat) instead of  check returned bools

2018-03-07 10:57 UTC, IgorKheidorov commented on task_DEV-3/EntryPoint.cs
> +            bool checkIntervalBase = baseOfNewSystem > 2 && baseOfNewSystem < 20;
>=2 and <=20 i suppose, this is bug

2018-03-07 10:57 UTC, IgorKheidorov commented on task_DEV-3/ConverterToOtherSystem.cs
> +        /// <returns>the converted number</returns>
Better name is GetConvertedNumber

2018-03-07 10:57 UTC, IgorKheidorov commented on task_DEV-3/ConverterToOtherSystem.cs
> +
Bad name, what do you mean by GetDigit? 'A' or 'B' are not digits

2018-03-08 19:25 UTC, AlexanderSoroka commented on task_DEV-3/ConverterToOtherSystem.cs
> +        /// <returns>the converted number</returns>
or just Convert

2018-03-08 19:25 UTC, AlexanderSoroka commented on task_DEV-3/EntryPoint.cs
> +                if (!(args.Length == 2))
useless check

2018-03-16 12:58 UTC, merged